# Bottango error code constants

NONE = 0
EFFECTOR_NOT_FOUND = 1
EFFECTOR_POOL_FULL = 2
UNKNOWN_COMMAND = 3
INVALID_PARAMS = 4
OUT_OF_MEMORY = 5
SD_ERROR = 6
DOWNLOAD_ERROR = 7
ANIMATION_ERROR = 8
RELAY_ERROR = 9
